# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdAccountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('receive', '입금'), ('pay', '출금')], max_length=10)),
                ('category', models.CharField(choices=[('salary', '월급'), ('foodExpenses', '식비'), ('default', '기타')], default='default', max_length=10)),
                ('priority', models.SmallIntegerField(default=0)),
                ('memo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-priority',),
            },
        ),
    ]
